### ISSUE TITLE
handle _blank

### ISSUE THREAD

**Issue by stephanos** [kibu-australia/pushy#2]
Opening a link in a new tab is usually done with `target="_blank"`, but currently the click event handler just ignores this property and handles it like any other click.

I think there should be a special condition added for this. What do you think?

**Comment by wavejumper** [comment]
Thanks for raising this issue.

Agreed that the click event should ignore any elements with this attribute. I have updated logic in 41c52cd6137c60ca8d829419807a95958e6abfc1
