### ISSUE TITLE
Don't trigger on right click

### ISSUE THREAD

**Issue by deadghost** [kibu-australia/pushy#22]
Triggering the event on right click makes it impossible to do the usual right-click actions (copy, inspect, etc). Either don't do this by default or make it an option.

See: https://github.com/kibu-australia/pushy/pull/17

**Comment by wavejumper** [comment]
:+1: - I think this is reasonable and have replied to open PR

**Comment by wavejumper** [comment]
Merged #6 thanks to @piranha

I'll bump pushy version tonight
