### ISSUE TITLE
Not updating URL location bar

### ISSUE THREAD

**Issue by al3x** [kibu-australia/pushy#4]
I'm using pushy 0.3.0 with secretary 1.2.3 exactly as per the README. I'm able to navigate between routes just fine in my app, but the URL location bar doesn't update as one would expect with a `pushState` event. Is this a known issue?

**Comment by al3x** [comment]
This must be an issue in Secretary, or in my particular use of that library. I swapped it out for Bidi and pushState behavior is working as expected. Thanks for a nice library!

**Comment by wavejumper** [comment]
Glad to see you got it to work :)

I also use Bidi in my projects with pushy, however the test suite uses secretary 1.2.1 and the `get-token` method correctly returns the current location.

I'll see what changed in 1.2.3 of secretary and investigate when I have time later this week.
